name: Build Custom EPG

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install lxml requests unidecode

      - name: Build EPG
        env:
          M3U_URL: ${{ vars.M3U_URL }}
          EPG_REGION: ${{ vars.EPG_REGION || 'US' }}
        run: |
          set -euo pipefail
          python scripts/build_epg.py

      - name: Commit & push if changed
        run: |
          set -euo pipefail
          git config user.name "epg-bot"
          git config user.email "epg-bot@example.com"
          git add epg/epg.xml || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Auto-build custom EPG"
          git push
